"""Shared Schemas Package."""
from .common import ProvenanceEnum, HealthResponse
from .session import SessionSummary, UnitMetadata, StimulusPresentation
from .matrix import CanonicalSpikeMatrix
from .decoder import (
    DecoderTrainRequest,
    DecoderResult,
    FeatureImportanceRecord,
    DecoderDatasetSummary,
    DecoderDatasetDetail,
    DecodingTargetInfo,
    TargetsResponse,
    PerClassMetric,
    FoldMetric,
    CrossValidationMetrics,
    HeldOutMetrics,
    PerformanceResponse,
    ConfusionMatrixResponse,
    FeatureImportanceItem,
    FeatureImportanceResponse,
    RegionAggregation,
    UnitBrainMap,
    BrainMappingResponse,
    TrialPrediction,
    PredictionsResponse,
    TrialNeuralFeature,
    PredictionDetailResponse,
    DecoderRunResponse,
)
from .simulation import LIFSimConfig, LIFSimResult
from .comparison import (
    FiringStatistics,
    CorrelationAnalysis,
    PCAResult,
    ComparisonRequest,
    ComparisonResponse,
)

__all__ = [
    "ProvenanceEnum",
    "HealthResponse",
    "SessionSummary",
    "UnitMetadata",
    "StimulusPresentation",
    "CanonicalSpikeMatrix",
    "DecoderTrainRequest",
    "DecoderResult",
    "FeatureImportanceRecord",
    "DecoderDatasetSummary",
    "DecoderDatasetDetail",
    "DecodingTargetInfo",
    "TargetsResponse",
    "PerClassMetric",
    "FoldMetric",
    "CrossValidationMetrics",
    "HeldOutMetrics",
    "PerformanceResponse",
    "ConfusionMatrixResponse",
    "FeatureImportanceItem",
    "FeatureImportanceResponse",
    "RegionAggregation",
    "UnitBrainMap",
    "BrainMappingResponse",
    "TrialPrediction",
    "PredictionsResponse",
    "TrialNeuralFeature",
    "PredictionDetailResponse",
    "DecoderRunResponse",
    "LIFSimConfig",
    "LIFSimResult",
    "FiringStatistics",
    "CorrelationAnalysis",
    "PCAResult",
    "ComparisonRequest",
    "ComparisonResponse",
]
