"""Shared Schemas Package."""
from .common import ProvenanceEnum, HealthResponse
from .session import SessionSummary, UnitMetadata, StimulusPresentation
from .matrix import CanonicalSpikeMatrix
from .canonical import (
    SessionMetadata,
    TrialMetadata,
    CanonicalNeuralDataset,
    ExplorerSessionSummary,
    PCAPoint,
    PCAPoint as ExplorerPCAPoint,
    PCAResponse,
    HeatmapResponse,
    PopulationTraceResponse,
    UploadResponse,
)
from .decoder import (
    DecoderTrainRequest,
    DecoderResult,
    FeatureImportanceRecord,
    DecoderDatasetSummary,
    DecoderDatasetDetail,
    DecodingTargetInfo,
    TargetsResponse,
    PerClassMetric,
    FoldMetric,
    CrossValidationMetrics,
    HeldOutMetrics,
    PerformanceResponse,
    ConfusionMatrixResponse,
    FeatureImportanceItem,
    FeatureImportanceResponse,
    RegionAggregation,
    UnitBrainMap,
    BrainMappingResponse,
    TrialPrediction,
    PredictionsResponse,
    TrialNeuralFeature,
    PredictionDetailResponse,
    DecoderRunResponse,
)
from .simulation import (
    SimulationModeEnum,
    LIFSimConfig,
    LIFSimResult,
    LIFPopulationParams,
    SimulationRunRequest,
    SpikeEvent,
    MembranePotentialData,
    ISIStats,
    PopulationFiringRate,
    SimulationSummary,
    SimulationResponse,
)
from .comparison import (
    FiringStatistics,
    CorrelationAnalysis,
    PCAResult,
    ComparisonRequest,
    ComparisonResponse,
    ComparisonBaseRequest,
    ComparisonOverviewResponse,
    SessionComparisonResponse,
    PopulationComparisonResponse,
    ComparisonSessionOption,
    DatasetOverviewSummary,
    OverviewMetricDiff,
    RegionOverlapSummary,
    StimulusOverlapSummary,
    PopulationSimilarityBreakdown,
    SessionMetadataRecord,
    RegionComparisonItem,
    StimulusComparisonItem,
    DatasetPCAResult,
    PopulationStatsRecord,
    ActivityDistributionHistogram,
    RegionActivityItem,
    PCAPoint as ComparisonPCAPoint,
)

__all__ = [
    # Common & Session
    "ProvenanceEnum",
    "HealthResponse",
    "SessionSummary",
    "UnitMetadata",
    "StimulusPresentation",
    "CanonicalSpikeMatrix",
    # Explorer Canonical
    "SessionMetadata",
    "TrialMetadata",
    "CanonicalNeuralDataset",
    "ExplorerSessionSummary",
    "PCAPoint",
    "ExplorerPCAPoint",
    "PCAResponse",
    "HeatmapResponse",
    "PopulationTraceResponse",
    "UploadResponse",
    # Decoder
    "DecoderTrainRequest",
    "DecoderResult",
    "FeatureImportanceRecord",
    "DecoderDatasetSummary",
    "DecoderDatasetDetail",
    "DecodingTargetInfo",
    "TargetsResponse",
    "PerClassMetric",
    "FoldMetric",
    "CrossValidationMetrics",
    "HeldOutMetrics",
    "PerformanceResponse",
    "ConfusionMatrixResponse",
    "FeatureImportanceItem",
    "FeatureImportanceResponse",
    "RegionAggregation",
    "UnitBrainMap",
    "BrainMappingResponse",
    "TrialPrediction",
    "PredictionsResponse",
    "TrialNeuralFeature",
    "PredictionDetailResponse",
    "DecoderRunResponse",
    # Simulation
    "SimulationModeEnum",
    "LIFSimConfig",
    "LIFSimResult",
    "LIFPopulationParams",
    "SimulationRunRequest",
    "SpikeEvent",
    "MembranePotentialData",
    "ISIStats",
    "PopulationFiringRate",
    "SimulationSummary",
    "SimulationResponse",
    # Comparison
    "FiringStatistics",
    "CorrelationAnalysis",
    "PCAResult",
    "ComparisonRequest",
    "ComparisonResponse",
    "ComparisonBaseRequest",
    "ComparisonOverviewResponse",
    "SessionComparisonResponse",
    "PopulationComparisonResponse",
    "ComparisonSessionOption",
    "DatasetOverviewSummary",
    "OverviewMetricDiff",
    "RegionOverlapSummary",
    "StimulusOverlapSummary",
    "PopulationSimilarityBreakdown",
    "SessionMetadataRecord",
    "RegionComparisonItem",
    "StimulusComparisonItem",
    "DatasetPCAResult",
    "PopulationStatsRecord",
    "ActivityDistributionHistogram",
    "RegionActivityItem",
    "ComparisonPCAPoint",
]
